# Generated by Django 3.2 on 2024-02-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SportsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release', models.DateTimeField(verbose_name='Release Date')),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sports')),
            ],
        ),
        migrations.CreateModel(
            name='RPGGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release', models.DateTimeField(verbose_name='Release Date')),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.rpg')),
            ],
        ),
    ]
