# Generated by Django 3.2 on 2024-02-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20240207_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpggame',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpggame', to='games.rpg'),
        ),
        migrations.AlterField(
            model_name='shootergame',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shootergame', to='games.shooter'),
        ),
        migrations.AlterField(
            model_name='sportsgame',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportsgame', to='games.sports'),
        ),
    ]
